# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 622)
        MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        MainWindow.setToolTipDuration(-4)
        MainWindow.setStyleSheet("background-color: #444;\n"
"color: #0FF;\n"
"font-family: Arial;\n"
"font-size: 25px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bGenerateTabs = QtWidgets.QPushButton(self.centralwidget)
        self.bGenerateTabs.setMinimumSize(QtCore.QSize(250, 40))
        self.bGenerateTabs.setMaximumSize(QtCore.QSize(500, 1000))
        self.bGenerateTabs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bGenerateTabs.setStyleSheet("QPushButton {\n"
"background-color: #666;\n"
"border-radius: 20px;\n"
"color: #0FF;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"margin: 0 85px 0 45px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #555;\n"
"}")
        self.bGenerateTabs.setObjectName("bGenerateTabs")
        self.gridLayout.addWidget(self.bGenerateTabs, 3, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(400, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(800, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.cNotesPerBeat = QtWidgets.QComboBox(self.frame_3)
        self.cNotesPerBeat.setGeometry(QtCore.QRect(190, 10, 161, 40))
        self.cNotesPerBeat.setMinimumSize(QtCore.QSize(0, 40))
        self.cNotesPerBeat.setMaximumSize(QtCore.QSize(200, 100))
        self.cNotesPerBeat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cNotesPerBeat.setStyleSheet("background-color: #333;\n"
"border-radius: 10px;\n"
"color: #0FF;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"")
        self.cNotesPerBeat.setObjectName("cNotesPerBeat")
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setMinimumSize(QtCore.QSize(500, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(500, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.bGoPremium = QtWidgets.QPushButton(self.frame_7)
        self.bGoPremium.setGeometry(QtCore.QRect(50, 10, 200, 31))
        self.bGoPremium.setMinimumSize(QtCore.QSize(30, 0))
        self.bGoPremium.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bGoPremium.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"color: #FFFF7F;\n"
"}")
        self.bGoPremium.setObjectName("bGoPremium")
        self.bDonate = QtWidgets.QPushButton(self.frame_7)
        self.bDonate.setGeometry(QtCore.QRect(300, 10, 91, 31))
        self.bDonate.setMinimumSize(QtCore.QSize(20, 0))
        self.bDonate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bDonate.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"color: #FFFF7F;\n"
"}")
        self.bDonate.setObjectName("bDonate")
        self.gridLayout.addWidget(self.frame_7, 5, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.lFretColor = QtWidgets.QPushButton(self.frame_4)
        self.lFretColor.setGeometry(QtCore.QRect(140, 10, 41, 41))
        self.lFretColor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lFretColor.setStyleSheet("background-color: rgb(255, 255, 255); border: none;")
        self.lFretColor.setText("")
        self.lFretColor.setObjectName("lFretColor")
        self.gridLayout.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(800, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.eBPM = QtWidgets.QLineEdit(self.frame_2)
        self.eBPM.setGeometry(QtCore.QRect(90, 10, 81, 41))
        self.eBPM.setMaximumSize(QtCore.QSize(800, 150))
        self.eBPM.setStyleSheet("background-color: #333;\n"
"border-radius: 10px;\n"
"color: #DDD;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"")
        self.eBPM.setText("")
        self.eBPM.setObjectName("eBPM")
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(800, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.bTabsFile = QtWidgets.QPushButton(self.frame)
        self.bTabsFile.setGeometry(QtCore.QRect(120, 10, 361, 41))
        self.bTabsFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bTabsFile.setStyleSheet("background-color: #333;\n"
"border-radius: 10px;\n"
"color: #888;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"text-align: left;\n"
"padding-left: 3px;")
        self.bTabsFile.setObjectName("bTabsFile")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(800, 200))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 191, 41))
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.lPlayedFretColor = QtWidgets.QPushButton(self.frame_5)
        self.lPlayedFretColor.setGeometry(QtCore.QRect(210, 10, 41, 41))
        self.lPlayedFretColor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lPlayedFretColor.setStyleSheet("background-color: rgb(255, 255, 255); border: none;")
        self.lPlayedFretColor.setText("")
        self.lPlayedFretColor.setObjectName("lPlayedFretColor")
        self.gridLayout.addWidget(self.frame_5, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 820, 29))
        self.menuBar.setStyleSheet("font-size: 20px;\n"
"color: #DDD;\n"
"")
        self.menuBar.setObjectName("menuBar")
        self.menuAdvanced = QtWidgets.QMenu(self.menuBar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        self.menuConfigurations = QtWidgets.QMenu(self.menuBar)
        self.menuConfigurations.setObjectName("menuConfigurations")
        MainWindow.setMenuBar(self.menuBar)
        self.aMoreOptions = QtWidgets.QAction(MainWindow)
        self.aMoreOptions.setObjectName("aMoreOptions")
        self.actionGo_Premium = QtWidgets.QAction(MainWindow)
        self.actionGo_Premium.setObjectName("actionGo_Premium")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.aSaveConfig = QtWidgets.QAction(MainWindow)
        self.aSaveConfig.setObjectName("aSaveConfig")
        self.aRestoreConfig = QtWidgets.QAction(MainWindow)
        self.aRestoreConfig.setObjectName("aRestoreConfig")
        self.aDeleteConfig = QtWidgets.QAction(MainWindow)
        self.aDeleteConfig.setObjectName("aDeleteConfig")
        self.aResetDefault = QtWidgets.QAction(MainWindow)
        self.aResetDefault.setObjectName("aResetDefault")
        self.menuAdvanced.addAction(self.aMoreOptions)
        self.menuConfigurations.addAction(self.aSaveConfig)
        self.menuConfigurations.addAction(self.aRestoreConfig)
        self.menuConfigurations.addAction(self.aDeleteConfig)
        self.menuConfigurations.addAction(self.aResetDefault)
        self.menuBar.addAction(self.menuAdvanced.menuAction())
        self.menuBar.addAction(self.menuConfigurations.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bGenerateTabs.setText(_translate("MainWindow", "Generate"))
        self.label_16.setText(_translate("MainWindow", "Notes per beat:"))
        self.bGoPremium.setText(_translate("MainWindow", "Go Premium"))
        self.bDonate.setText(_translate("MainWindow", "Donate"))
        self.label_19.setText(_translate("MainWindow", "Fret color:"))
        self.label_15.setText(_translate("MainWindow", "BPM:"))
        self.eBPM.setPlaceholderText(_translate("MainWindow", "124"))
        self.label_8.setText(_translate("MainWindow", "Tabs file:"))
        self.bTabsFile.setText(_translate("MainWindow", "Drop tabs file here"))
        self.label_20.setText(_translate("MainWindow", "Played fret color:"))
        self.menuAdvanced.setTitle(_translate("MainWindow", "More Options"))
        self.menuConfigurations.setTitle(_translate("MainWindow", "Configurations"))
        self.aMoreOptions.setText(_translate("MainWindow", "More Options"))
        self.actionGo_Premium.setText(_translate("MainWindow", "Go Premium"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.aSaveConfig.setText(_translate("MainWindow", "Save config"))
        self.aRestoreConfig.setText(_translate("MainWindow", "Restore config"))
        self.aDeleteConfig.setText(_translate("MainWindow", "Delete config"))
        self.aResetDefault.setText(_translate("MainWindow", "Reset default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
