# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messageWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageWindow(object):
    def setupUi(self, MessageWindow):
        MessageWindow.setObjectName("MessageWindow")
        MessageWindow.resize(508, 190)
        MessageWindow.setMinimumSize(QtCore.QSize(300, 0))
        MessageWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        MessageWindow.setToolTipDuration(-4)
        MessageWindow.setStyleSheet("QMainWindow, QWidget {\n"
"background-color: #555;\n"
"color: #FFF;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"border-radius: 10px\n"
"}\n"
"QPushButton {\n"
"background-color: #444;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #666;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MessageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(30, 0, 0, 70)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.symbol = QtWidgets.QFrame(self.frame_3)
        self.symbol.setMinimumSize(QtCore.QSize(30, 30))
        self.symbol.setMaximumSize(QtCore.QSize(30, 30))
        self.symbol.setStyleSheet("background-color: #FFF;\n"
"border-radius: 15px;")
        self.symbol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.symbol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.symbol.setObjectName("symbol")
        self.verticalLayout.addWidget(self.symbol)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.message = QtWidgets.QTextEdit(self.frame_2)
        self.message.setMinimumSize(QtCore.QSize(0, 140))
        self.message.setMaximumSize(QtCore.QSize(16777215, 140))
        self.message.setStyleSheet("padding: 15px 10px;")
        self.message.setReadOnly(True)
        self.message.setObjectName("message")
        self.horizontalLayout_2.addWidget(self.message)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setMinimumSize(QtCore.QSize(100, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setMaximumSize(QtCore.QSize(100, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.acceptButton = QtWidgets.QPushButton(self.frame_8)
        self.acceptButton.setMaximumSize(QtCore.QSize(100, 40))
        self.acceptButton.setStyleSheet("")
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_3.addWidget(self.acceptButton)
        self.gridLayout.addWidget(self.frame_8, 1, 0, 1, 2)
        MessageWindow.setCentralWidget(self.centralwidget)
        self.aMoreOptions = QtWidgets.QAction(MessageWindow)
        self.aMoreOptions.setObjectName("aMoreOptions")
        self.actionGo_Premium = QtWidgets.QAction(MessageWindow)
        self.actionGo_Premium.setObjectName("actionGo_Premium")
        self.actionDonate = QtWidgets.QAction(MessageWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.aSaveConfig = QtWidgets.QAction(MessageWindow)
        self.aSaveConfig.setObjectName("aSaveConfig")
        self.aRestoreConfig = QtWidgets.QAction(MessageWindow)
        self.aRestoreConfig.setObjectName("aRestoreConfig")
        self.aDeleteConfig = QtWidgets.QAction(MessageWindow)
        self.aDeleteConfig.setObjectName("aDeleteConfig")
        self.aResetDefault = QtWidgets.QAction(MessageWindow)
        self.aResetDefault.setObjectName("aResetDefault")

        self.retranslateUi(MessageWindow)
        QtCore.QMetaObject.connectSlotsByName(MessageWindow)

    def retranslateUi(self, MessageWindow):
        _translate = QtCore.QCoreApplication.translate
        MessageWindow.setWindowTitle(_translate("MessageWindow", "MainWindow"))
        self.message.setHtml(_translate("MessageWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Input number of strings:</span></p></body></html>"))
        self.acceptButton.setText(_translate("MessageWindow", "Accept"))
        self.aMoreOptions.setText(_translate("MessageWindow", "More Options"))
        self.actionGo_Premium.setText(_translate("MessageWindow", "Go Premium"))
        self.actionDonate.setText(_translate("MessageWindow", "Donate"))
        self.aSaveConfig.setText(_translate("MessageWindow", "Save config"))
        self.aRestoreConfig.setText(_translate("MessageWindow", "Restore config"))
        self.aDeleteConfig.setText(_translate("MessageWindow", "Delete config"))
        self.aResetDefault.setText(_translate("MessageWindow", "Reset default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MessageWindow = QtWidgets.QMainWindow()
    ui = Ui_MessageWindow()
    ui.setupUi(MessageWindow)
    MessageWindow.show()
    sys.exit(app.exec_())
