# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textLineInputWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextLineInputWindow(object):
    def setupUi(self, TextLineInputWindow):
        TextLineInputWindow.setObjectName("TextLineInputWindow")
        TextLineInputWindow.resize(412, 177)
        TextLineInputWindow.setMinimumSize(QtCore.QSize(300, 0))
        TextLineInputWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        TextLineInputWindow.setToolTipDuration(-4)
        TextLineInputWindow.setStyleSheet("QMainWindow, QWidget {\n"
"background-color: #555;\n"
"color: #FFF;\n"
"font-family: Arial;\n"
"font-size: 25px;\n"
"border-radius: 10px\n"
"}\n"
"QPushButton {\n"
"background-color: #444;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #666;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(TextLineInputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_2.setContentsMargins(30, 10, 30, 10)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_9)
        self.frame_3.setStyleSheet("background-color: #888;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(self.frame_3)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_9, 1, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.message = QtWidgets.QTextEdit(self.frame)
        self.message.setGeometry(QtCore.QRect(20, 10, 471, 81))
        self.message.setReadOnly(True)
        self.message.setObjectName("message")
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 3)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leftButton = QtWidgets.QPushButton(self.frame_8)
        self.leftButton.setMaximumSize(QtCore.QSize(100, 40))
        self.leftButton.setStyleSheet("")
        self.leftButton.setObjectName("leftButton")
        self.horizontalLayout_3.addWidget(self.leftButton)
        self.rightButton = QtWidgets.QPushButton(self.frame_8)
        self.rightButton.setMaximumSize(QtCore.QSize(100, 40))
        self.rightButton.setStyleSheet("")
        self.rightButton.setObjectName("rightButton")
        self.horizontalLayout_3.addWidget(self.rightButton)
        self.gridLayout.addWidget(self.frame_8, 2, 0, 1, 3)
        TextLineInputWindow.setCentralWidget(self.centralwidget)
        self.aMoreOptions = QtWidgets.QAction(TextLineInputWindow)
        self.aMoreOptions.setObjectName("aMoreOptions")
        self.actionGo_Premium = QtWidgets.QAction(TextLineInputWindow)
        self.actionGo_Premium.setObjectName("actionGo_Premium")
        self.actionDonate = QtWidgets.QAction(TextLineInputWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.aSaveConfig = QtWidgets.QAction(TextLineInputWindow)
        self.aSaveConfig.setObjectName("aSaveConfig")
        self.aRestoreConfig = QtWidgets.QAction(TextLineInputWindow)
        self.aRestoreConfig.setObjectName("aRestoreConfig")
        self.aDeleteConfig = QtWidgets.QAction(TextLineInputWindow)
        self.aDeleteConfig.setObjectName("aDeleteConfig")
        self.aResetDefault = QtWidgets.QAction(TextLineInputWindow)
        self.aResetDefault.setObjectName("aResetDefault")

        self.retranslateUi(TextLineInputWindow)
        QtCore.QMetaObject.connectSlotsByName(TextLineInputWindow)

    def retranslateUi(self, TextLineInputWindow):
        _translate = QtCore.QCoreApplication.translate
        TextLineInputWindow.setWindowTitle(_translate("TextLineInputWindow", "MainWindow"))
        self.message.setHtml(_translate("TextLineInputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Input number of strings:</span></p></body></html>"))
        self.leftButton.setText(_translate("TextLineInputWindow", "Save"))
        self.rightButton.setText(_translate("TextLineInputWindow", "Cancel"))
        self.aMoreOptions.setText(_translate("TextLineInputWindow", "More Options"))
        self.actionGo_Premium.setText(_translate("TextLineInputWindow", "Go Premium"))
        self.actionDonate.setText(_translate("TextLineInputWindow", "Donate"))
        self.aSaveConfig.setText(_translate("TextLineInputWindow", "Save config"))
        self.aRestoreConfig.setText(_translate("TextLineInputWindow", "Restore config"))
        self.aDeleteConfig.setText(_translate("TextLineInputWindow", "Delete config"))
        self.aResetDefault.setText(_translate("TextLineInputWindow", "Reset default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextLineInputWindow = QtWidgets.QMainWindow()
    ui = Ui_TextLineInputWindow()
    ui.setupUi(TextLineInputWindow)
    TextLineInputWindow.show()
    sys.exit(app.exec_())
